### ISSUE TITLE
Newman Docker image doesn't include CryptoJS

### ISSUE THREAD

**Issue by sheluchin** [postmanlabs/newman-docker#15]
The Postman sandbox includes CryptoJS, but the Newman image does not. As a result, tests which use CryptoJS produce the following error: `EXCEPTION - ReferenceError: CryptoJS is not defined`.

**Comment by shamasis** [comment]
@elssar can you push the latest images and close this ticket?

**Comment by elssar** [comment]
@sheluchin thanks for reporting this. I have pushed images with the latest 1.x and 2.x releases of newman. Both have CryptoJS available in the sandbox.
