### ISSUE TITLE
Upgrade node version

### ISSUE THREAD

**Issue by elssar** [postmanlabs/newman-docker#30]
Node v4.3.0 is quite old and a lot of the nice/cool ES6 features aren't available, like default function parameters (#28 ).

Ideally, the user should be able to specify the node version while running the docker version. Maybe take a parameter in addition to the default newman parameters on docker run that specifies the node version.

**Comment by kunagpal** [comment]
Since the latter is not possible yet, it would make more sense to bump up to Node 6.11.0 LTS.

**Comment by miked0004** [comment]
Please consider introducing [ARG](https://docs.docker.com/engine/reference/builder/#arg) into your `Dockerfile` to allow overriding of the defaults.

```
ARG NODE_VERSION=4.3.2
ENV NODE_VERSION ${NODE_VERSION}
...
ARG NEWMAN_VERSION=3.7.6
ENV NEWMAN_VERSION ${NEWMAN_VERSION}
```

Which then provides this flexibility and reduces the need for your user base to duplicate your Dockerfile:
```
docker build \
    --build-arg NODE_VERSION=6.11.1 \
    --build-arg NEWMAN_VERSION=3.8.0 \
    --tag postman/newman_ubuntu1404_6111_380 \
    .
```

Thank you

**Comment by kunagpal** [comment]
@miked0004 Those were our thoughts initially, but any Node version overrides will require a download for the specified Node version. A cleaner way out would be to ship the docker images with Node LTS (v6.11.1 at the time of writing) and move to v8 in October when Node v8.x transitions to LTS.

**Comment by miked0004** [comment]
I agree. It's just that for our custom needs, it makes it a bit easier manage. 
Also, the ARG default would ensure this would not change any current behavior. Is it only an extension point for custom builders.
