### ISSUE TITLE
Docs: /etc/postman or /etc/newman

### ISSUE THREAD

**Issue by aarcro** [postmanlabs/newman-docker#51]
The docker hub pages https://hub.docker.com/r/postman/newman_alpine33/ and https://hub.docker.com/r/postman/newman_ubuntu1404/ aren't clear on if the collections mount should be /etc/newman or /etc/postman. Looks like /etc/newman is the correct place.

Can you update the Docs in Docker hub?

**Comment by kunagpal** [comment]
@aarcro It's `/etc/newman`, and the updated docs are now avaialable here: https://github.com/postmanlabs/newman/tree/develop/docker/images
