### ISSUE TITLE
Upload new docker image to docker hub.

### ISSUE THREAD

**Issue by klubi** [postmanlabs/newman-docker#61]
Hi

Could you add new docker images to docker hub?
Also, would it be possible for those images to have 3.7.0 version of newman?

Thanks

**Comment by elssar** [comment]
Hey @klubi 

We've published images for the latest version of Newman (v3.7.1) for both Ubuntu and Alpine.
We're skipping v3.6.1, and v3.7.0 because of a bug that bloated the size of the images by ~400mb.
