### ISSUE TITLE
How to expose TCP port for remote access to image ?

### ISSUE THREAD

**Issue by pradeepkusingh** [postmanlabs/newman-docker#78]
How to expose TCP for remote access to the image ?  -H ? I am trying to deploy this image in cloud foundry and don't see any port exposed to have remote access enabled.

**Comment by kunagpal** [comment]
@pradeepkusingh While the Newman Docker images were not intended for the use case that you have described, you can build a custom docker image with Newman as a base, by including the following line at the beginning of your Dockerfile:
```
FROM postman/newman_alpine33:latest

# `newman` will be available as a CLI executable.
```

More details here: https://docs.docker.com/engine/reference/builder/#usage
