### ISSUE TITLE
Update newman to 3.9.1

### ISSUE THREAD

**Issue by barnesm999** [postmanlabs/newman-docker#81]
Newman is out of date in this docker image. Postman features such as Collection and Folder level pre request script / tests are not supported by the current version of Newman. 

Per npm Latest newman is https://www.npmjs.com/package/newman.

**Comment by cbarrerah-sogeti** [comment]
any update on this one?
Really important to set up Continuous integration with newman collections

**Comment by kunagpal** [comment]
@barnesm999 @cbarrerah-sogeti This has been resolved, you can update to v3.9.3, which is the latest version at the time of writing.
