### ISSUE TITLE
Node version is very old.  Might consider updating this image with latest stable nodejs version (8.9.4 at time of writing)

### ISSUE THREAD

**Issue by Laeconian** [postmanlabs/newman-docker#83]
https://github.com/postmanlabs/newman-docker/blob/f14b26ccc884e70efa8f28fcfddff24cf15e5a91/images/ubuntu1404/Dockerfile#L10

**Comment by Laeconian** [comment]
This caused me headaches setting up a CI solution for testing using postman collections.

**Comment by kunagpal** [comment]
Closing as a duplicate of #30
