### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hlubovac** [postmanlabs/newman-docker#86]
Perhaps this scenario isn't supported, but I get this error on subsequent runs (first run works).

Container created and started (parts of URLs omitted):

```
docker run --name "gateway-tests" -t "postman/newman_ubuntu1404" run "https://www.getpostman.com/collections/..." --environment="https://.../env2.json"
```

And I get test-run feedback:
![image](https://user-images.githubusercontent.com/3127736/36280273-0546a35e-1257-11e8-9b1b-271037189350.png)

... then that container gets stopped. When I start it again (`docker container start gateway-tests`), this is what I get:

![image](https://user-images.githubusercontent.com/3127736/36280313-1c9b57ca-1257-11e8-9a30-38c602937414.png)

But when I do this: `docker container start gateway-tests -i`, then all works just fine (like the first run).

**Comment by kunagpal** [comment]
https://github.com/postmanlabs/newman/issues/885
