### ISSUE TITLE
Question: getting reports

### ISSUE THREAD

**Issue by hlubovac** [postmanlabs/newman-docker#87]
I know about newman reporters, somewhat. Should there be a way to access report data (e.g. json) without having a mounted volume involved? Should there be a way to redirect the CLI somehow via docker run? Or, should there be a way to pass information about custom reporter, via docker-run? I'm trying to envision CI automation where a container would be launched to run a collection, then results would be delivered to the "caller" (the script that owns the process) to analyze test results. Is there a guide for something like this? Thanks.

**Comment by kunagpal** [comment]
Closing as a duplicate of #29
