### ISSUE TITLE
ENOENT: no such file or directory, open '  on CI env 

### ISSUE THREAD

**Issue by Thirumurugan19** [postmanlabs/newman-docker#92]
Newman works fine with local env and below unable to read data seen on Circle CI and exit . If anyone faced the problem and solution will be helpful.

#!/bin/bash -eo pipefail
newman run collections/test.json --environment collections/env_variable.json
unable to read data from file "collections/test.json"
ENOENT: no such file or directory, open 'collections/test.json'
Exited with code 1

**Comment by kunagpal** [comment]
Closing as a duplicate of #29

**Comment by kunagpal** [comment]
@Thirumurugan19 This happens when the file cannot be found at the specified path. Could you add `ls -ln` before the `newman run ...` command and confirm that the collections directory exists?
