### ISSUE TITLE
ECONNREFUSED 127.0.0.1:33333

### ISSUE THREAD

**Issue by Epoxboy** [postmanlabs/newman-docker#95]
Hi guys,

I've built a new image based on postman/newman_alpine33 image and just add a non-root user in order to run this container as a non-root user. When I run it on the host to test API services(also docker containers) on the same host, the test request response failed every time. 
e.g.:

when I try to hit http://localhost:33333/health I got the following error, but I can curl it directly when I ssh into the host.

04.  Error           connect ECONNREFUSED 127.0.0.1:33333                                                                 ", 
        "                      at request                                                                                           ", 
        "                      inside \"using localhost -hello-world-api\"  

and I've tried use hostname, host IP but all failed, errors are:

07.  Error           connect ETIMEDOUT 10.13.32.69:33333

13.  Error           getaddrinfo ENOTFOUND hostname hostname:33333

the API ports are all ported to the host when run the container up using -p argument.

What could be wrong?

Thank you!

**Comment by kunagpal** [comment]
@Epoxboy Could you share the command used here?

**Comment by Epoxboy** [comment]
Thank you for responding, i’ve solved problem as I should hit the container ‘s ip and port directly from another container, therefore, close this issue.
