### ISSUE TITLE
postman/newman_ubuntu1404: Unexpected token '#' at 1:1

### ISSUE THREAD

**Issue by vdespa** [postmanlabs/newman-docker#96]
I have just updated the postman/newman_ubuntu1404 and now I am getting this error message when running:

`docker run -t postman/newman_ubuntu1404 --url="https://www.getpostman.com/collections/8a0c9bc08f062d12dcda"`

The log output is:

> newman: the v2.x CLI options are deprecated. You should use newman run <path> [options] instead.
>         refer https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md for details.
> the file at /usr/bin/newman does not contain valid JSON data
> Unexpected token '#' at 1:1
> #!/usr/bin/env node
> ^

**Comment by kunagpal** [comment]
@vdespa This has been fixed with v3.9.4. Could you upgrade and confirm?
